### ISSUE TITLE
videos/tv shows that have been downloaded aren't protected

### ISSUE THREAD

**Issue by oneadvent** [killdash9/xbmc-parental-controls#2]
I am really not sure if this is a bug because I am not sure if you are trying to protect this. The Readme says "video sources" and a samba share (which is what I am using) is a video source. These shows are not effected by this addon. This is the major area I wish to control. Can you let me know if it is supposed to be protected?

**Comment by killdash9** [comment]
oneadvent, 

It is designed to protect video addons.  I assume your samba share is not done through an addon, you're just using the built-in xbmc support for shares.  If that is the case, this plugin will not help there.

**Comment by dethknite** [comment]
Really would love to have the functionality to media mapped over a NAS...

**Comment by dethknite** [comment]
Correct, they are samba shares, but ratings are provided via the TV/Movie ratings thetvdb/imdb.  It would be awesomer than awesome if you found a way to implement this with the samba shares.  True story..

**Comment by killdash9** [comment]
I have not been able to find a way to do this.  The addon works by intercepting python APIs for video plugins.  Since access to samba/NAS shares is done in the XBMC core and not through a plugin, I am unable to use this technique here.  Such a feature would have to be built into the core.
