### ISSUE TITLE
Frodo compatibility

### ISSUE THREAD

**Issue by fjakop** [killdash9/xbmc-parental-controls#3]
Hello, I really like your addon. Is it supposed to be compatible with XBMC 12? I do not get it working.

**Comment by nedking** [comment]
Hi Kildash9,

I like to use Parental Control addon in KODI 15.2. It is not working. Do you have any plans on working this code. If not, could you please guide me. I am a software programmer but not done any programming in KODI environment. Thanks. Ned

**Comment by killdash9** [comment]
I no longer have time to work on this, but may be able to answer any specific questions you have.

**Comment by nedking** [comment]
Please advise me what is needed to tweak in order to get it working in KODI
15.2. I am new in KODI environment but has a good software experience..

Regards,

Ned

**Comment by killdash9** [comment]
That is a general question not a specific one.  I don't have time to look into why it isn't working.
